# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Mia_pb2 as Mia__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Mia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MiaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/MiaGRPC.MiaService/CreateUser',
                request_serializer=Mia__pb2.SetUserRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.ReadUsers = channel.unary_unary(
                '/MiaGRPC.MiaService/ReadUsers',
                request_serializer=Mia__pb2.SetUserRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/MiaGRPC.MiaService/UpdateUser',
                request_serializer=Mia__pb2.SetUserRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/MiaGRPC.MiaService/DeleteUser',
                request_serializer=Mia__pb2.SetUserRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.CreateSvm = channel.unary_unary(
                '/MiaGRPC.MiaService/CreateSvm',
                request_serializer=Mia__pb2.SetSvmRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetSvmsResponse.FromString,
                _registered_method=True)
        self.ReadSvms = channel.unary_unary(
                '/MiaGRPC.MiaService/ReadSvms',
                request_serializer=Mia__pb2.SetSvmRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetSvmsResponse.FromString,
                _registered_method=True)
        self.UpdateSvm = channel.unary_unary(
                '/MiaGRPC.MiaService/UpdateSvm',
                request_serializer=Mia__pb2.SetSvmRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetSvmsResponse.FromString,
                _registered_method=True)
        self.DeleteSvm = channel.unary_unary(
                '/MiaGRPC.MiaService/DeleteSvm',
                request_serializer=Mia__pb2.SetSvmRequest.SerializeToString,
                response_deserializer=Mia__pb2.GetSvmsResponse.FromString,
                _registered_method=True)
        self.TrainSvm = channel.unary_unary(
                '/MiaGRPC.MiaService/TrainSvm',
                request_serializer=Mia__pb2.SetSvmRequest.SerializeToString,
                response_deserializer=Mia__pb2.MiaResponse.FromString,
                _registered_method=True)
        self.ReadIndex = channel.unary_unary(
                '/MiaGRPC.MiaService/ReadIndex',
                request_serializer=Mia__pb2.IndexRequest.SerializeToString,
                response_deserializer=Mia__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.ReadData = channel.unary_stream(
                '/MiaGRPC.MiaService/ReadData',
                request_serializer=Mia__pb2.DataRequest.SerializeToString,
                response_deserializer=Mia__pb2.ImageData.FromString,
                _registered_method=True)
        self.SetData = channel.stream_unary(
                '/MiaGRPC.MiaService/SetData',
                request_serializer=Mia__pb2.SetDataRequest.SerializeToString,
                response_deserializer=Mia__pb2.MiaResponse.FromString,
                _registered_method=True)
        self.RemoveData = channel.unary_unary(
                '/MiaGRPC.MiaService/RemoveData',
                request_serializer=Mia__pb2.RemoveDataRequest.SerializeToString,
                response_deserializer=Mia__pb2.MiaResponse.FromString,
                _registered_method=True)
        self.Recognize = channel.stream_stream(
                '/MiaGRPC.MiaService/Recognize',
                request_serializer=Mia__pb2.RecognitionRequest.SerializeToString,
                response_deserializer=Mia__pb2.RecognitionResponse.FromString,
                _registered_method=True)
        self.RecognizeSingle = channel.stream_stream(
                '/MiaGRPC.MiaService/RecognizeSingle',
                request_serializer=Mia__pb2.RecognizeSingleRequest.SerializeToString,
                response_deserializer=Mia__pb2.RecognitionResponse.FromString,
                _registered_method=True)


class MiaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """/////////////////////////////////USER/////////////////////////////////////////////

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSvm(self, request, context):
        """/////////////////////////////////SVM/////////////////////////////////////////////

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSvms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSvm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSvm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainSvm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadIndex(self, request, context):
        """///////////////////////////////IMAGES///////////////////////////////////////////////

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request_iterator, context):
        """///////////////////////////////RECOGNITION///////////////////////////////////////////////

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeSingle(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=Mia__pb2.SetUserRequest.FromString,
                    response_serializer=Mia__pb2.GetUsersResponse.SerializeToString,
            ),
            'ReadUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadUsers,
                    request_deserializer=Mia__pb2.SetUserRequest.FromString,
                    response_serializer=Mia__pb2.GetUsersResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=Mia__pb2.SetUserRequest.FromString,
                    response_serializer=Mia__pb2.GetUsersResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=Mia__pb2.SetUserRequest.FromString,
                    response_serializer=Mia__pb2.GetUsersResponse.SerializeToString,
            ),
            'CreateSvm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSvm,
                    request_deserializer=Mia__pb2.SetSvmRequest.FromString,
                    response_serializer=Mia__pb2.GetSvmsResponse.SerializeToString,
            ),
            'ReadSvms': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSvms,
                    request_deserializer=Mia__pb2.SetSvmRequest.FromString,
                    response_serializer=Mia__pb2.GetSvmsResponse.SerializeToString,
            ),
            'UpdateSvm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSvm,
                    request_deserializer=Mia__pb2.SetSvmRequest.FromString,
                    response_serializer=Mia__pb2.GetSvmsResponse.SerializeToString,
            ),
            'DeleteSvm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSvm,
                    request_deserializer=Mia__pb2.SetSvmRequest.FromString,
                    response_serializer=Mia__pb2.GetSvmsResponse.SerializeToString,
            ),
            'TrainSvm': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainSvm,
                    request_deserializer=Mia__pb2.SetSvmRequest.FromString,
                    response_serializer=Mia__pb2.MiaResponse.SerializeToString,
            ),
            'ReadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadIndex,
                    request_deserializer=Mia__pb2.IndexRequest.FromString,
                    response_serializer=Mia__pb2.IndexResponse.SerializeToString,
            ),
            'ReadData': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=Mia__pb2.DataRequest.FromString,
                    response_serializer=Mia__pb2.ImageData.SerializeToString,
            ),
            'SetData': grpc.stream_unary_rpc_method_handler(
                    servicer.SetData,
                    request_deserializer=Mia__pb2.SetDataRequest.FromString,
                    response_serializer=Mia__pb2.MiaResponse.SerializeToString,
            ),
            'RemoveData': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveData,
                    request_deserializer=Mia__pb2.RemoveDataRequest.FromString,
                    response_serializer=Mia__pb2.MiaResponse.SerializeToString,
            ),
            'Recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=Mia__pb2.RecognitionRequest.FromString,
                    response_serializer=Mia__pb2.RecognitionResponse.SerializeToString,
            ),
            'RecognizeSingle': grpc.stream_stream_rpc_method_handler(
                    servicer.RecognizeSingle,
                    request_deserializer=Mia__pb2.RecognizeSingleRequest.FromString,
                    response_serializer=Mia__pb2.RecognitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MiaGRPC.MiaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MiaGRPC.MiaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MiaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/CreateUser',
            Mia__pb2.SetUserRequest.SerializeToString,
            Mia__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/ReadUsers',
            Mia__pb2.SetUserRequest.SerializeToString,
            Mia__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/UpdateUser',
            Mia__pb2.SetUserRequest.SerializeToString,
            Mia__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/DeleteUser',
            Mia__pb2.SetUserRequest.SerializeToString,
            Mia__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSvm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/CreateSvm',
            Mia__pb2.SetSvmRequest.SerializeToString,
            Mia__pb2.GetSvmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSvms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/ReadSvms',
            Mia__pb2.SetSvmRequest.SerializeToString,
            Mia__pb2.GetSvmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSvm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/UpdateSvm',
            Mia__pb2.SetSvmRequest.SerializeToString,
            Mia__pb2.GetSvmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSvm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/DeleteSvm',
            Mia__pb2.SetSvmRequest.SerializeToString,
            Mia__pb2.GetSvmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainSvm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/TrainSvm',
            Mia__pb2.SetSvmRequest.SerializeToString,
            Mia__pb2.MiaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/ReadIndex',
            Mia__pb2.IndexRequest.SerializeToString,
            Mia__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiaGRPC.MiaService/ReadData',
            Mia__pb2.DataRequest.SerializeToString,
            Mia__pb2.ImageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/MiaGRPC.MiaService/SetData',
            Mia__pb2.SetDataRequest.SerializeToString,
            Mia__pb2.MiaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiaGRPC.MiaService/RemoveData',
            Mia__pb2.RemoveDataRequest.SerializeToString,
            Mia__pb2.MiaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MiaGRPC.MiaService/Recognize',
            Mia__pb2.RecognitionRequest.SerializeToString,
            Mia__pb2.RecognitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeSingle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MiaGRPC.MiaService/RecognizeSingle',
            Mia__pb2.RecognizeSingleRequest.SerializeToString,
            Mia__pb2.RecognitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
